local:
    mercury_url:              'http://localhost:11323'
    lithium_url:              ''
    bloom_url:                'http://localhost:49940'
    bloom_status_url:         'http://localhost:49940/internal/status/api'
    publish_site:             'http://localhost:48940'
    origin:                   'http://localhost:31423'
    sherpa:                   'http://localhost:8096'
    alcatraz:                 'http://localhost:5681'
    playlist_vodcrid:         '301871'
    irdeto_catchup_rtmpe:     '1/800735/2345#001'
    irdeto_archive_f4m:       '1/700434/13666cdfecb940a786045a980b807d00#001'
    user_id:                  '1237847'
ft02:
    alcatraz_url:             'http://test-alcatraz.itv.com'
    mercury_url:              'http://test-mercury.itv.com'
    secure_mercury_url:       'http://test-secure.mercury.itv.com'
    lithium_url:              'http://test-lithium-news.itv.com'
    bloom_status_url:         'http://bloomcms.itvft02.ads/internal/status/api'
    ftp_host:                 's01-itvonlineftp.itv.com'
    ftp_login:                'mercuryftp'
    ftp_password:             '9d$]q1H&g+\>'
    pay_metadata:             'http://s01-onramp.itv.com/Metadata/CatchupAndArchiveNew.meta'
    non_pay_metadata:         'http://s01-onramp.itv.com/Metadata/CatchupAndArchive.meta'
    irdeto_pay_metadata:      'http://s01-onramp.itv.com/Metadata/CatchupAndArchivePay.meta'
    temp_folder:              '/tmp/mdr'
    generic_production:       '1/805537/320d95e6185e448abcf7e856efb6236e#001'
    youview_production:       '1/805537/320d95e6185e448abcf7e856efb6236e#001'
    dotcom_catchup_rtmpe:     '1/805537/320d95e6185e448abcf7e856efb6236e#001'
    dotcom_archive_rtmpe:     ''
    user_id:                  '1237847'
    itv1_vodcrid:             '328123'
    itv2_vodcrid:             '328126'
    itv3_vodcrid:             '328128'
    itv4_vodcrid:             '328132'
    citv_vodcrid:             '328135'
    itv1_production:          '1/368199/ebf7f12cf6204721b0a12eb0aec6dfe7#001'
    itv2_production:          '1/896647/b7ceeee5b60d47fabcfc70ec6c86df3e#001'
    itv3_production:          '1/730793/9ebfb13eea7043a5a1a158db0863473c#001'
    itv4_production:          '1/675188/29b2d2f1dc3e4dfaa9c05209c353bf65#001'
    citv_production:          '1/137741/c0960f4948924220a069d84b06029a5b#001'
    absolute_break_pattern:   '1/796091/1c2694ea69752abfa4c5c7d92#001'
    generic_break_pattern_1:  '1/986923/2bac54605abecc633cef9059c#001'
    generic_break_pattern_2:  '1/137741/c0960f4948924220a069d84b06029a5b#001'
    duration_break_pattern:   '1/524316/f12094304899ada2247b7c633#001'
    freesat_production:       '328120'
i01:
    alcatraz_url:             'http://i01-alcatraz.itv.com'
    mercury_url:              'http://i01-mercury.itv.com'
    secure_mercury_url:       'http://i01-secure.mercury.itv.com'
    lithium_url:              'http://i01-lithium-news.itv.com'
    bloom_status_url:         'http://bloomcms.itvint01.ads/internal/status/api'
    temp_folder:              '/tmp/mdr'
    generic_production:       '1/840560/253114be3af4196c5926f634c#001'
    youview_production:       '2/268328/159c8#001'
    dotcom_catchup_rtmpe:     '1/419662/aac254712a8b8eb4934b22840#001'
    dotcom_archive_rtmpe:     '1/8670/0001#001'
    user_id:                  '12448' # ben.snape@itv.com / password
    absolute_break_pattern:   '1/132874/799e2476cb66b2fc89139edbe#001'
    generic_break_pattern_1:  '1/439949/b324e4de6b55da5e97c78640e#001'
    generic_break_pattern_2:  '1/797959/067694164994a59e5e3364b35#001'
    duration_break_pattern:   '1/274865/e8cb948ce9dcf285dfa935109#001'
    freesat_production:       '324074'
live:
    alcatraz_url:             'http://alcatraz.itv.com'
    mercury_url:              'http://mercury.itv.com'
    lithium_url:              'http://lithium-news.itv.com'
    bloom_status_url:         'http://bloomcms.itvonline.ads/internal/status/api'
    temp_folder:              '/tmp/mdr'
    generic_production:       '2/1780/0001#001'
    youview_production:       '2/1780/0001#001'
    dotcom_catchup_rtmpe:     '2/1780/0001#001'
    dotcom_archive_rtmpe:     ''
    user_id:                  '1200432'
