local: 
    mercury_url:          'http://localhost:11323'
    lithium_url:          ''
    bloom_url:            'http://localhost:49940' 
    bloom_status_url:     'http://localhost:49940/internal/status/api'
    publish_site:         'http://localhost:48940'
    origin:               'http://localhost:31423'
    sherpa:               'http://localhost:8096'
    alcatraz:             'http://localhost:5681'
    playlist_vodcrid:     '301871'
    playlist_hds_vodcrid: '303312'
    playlist_prodid:      '1/800735/2345#001'
    playlist_hds_prodid:  'Y/1774/0004/Z'
    user_id:              '1237847'
test:
    mercury_url:          'http://test-mercury.itv.com'
    lithium_url:          'http://test-lithium-news.itv.com'
    bloom_status_url:     'http://bloomcms.itvft02.ads/internal/status/api'
    ftp_host:             's01-itvonlineftp.itv.com'
    ftp_login:            'mercuryftp'
    ftp_password:         '9d$]q1H&g+\>'
    pay_metadata:         'http://s01-onramp.itv.com/Metadata/CatchupAndArchiveNew.meta'
    non_pay_metadata:     'http://s01-onramp.itv.com/Metadata/CatchupAndArchive.meta'
    irdeto_pay_metadata:  'http://s01-onramp.itv.com/Metadata/CatchupAndArchivePay.meta'
    temp_folder:          '/tmp/mdr'
    playlist_vodcrid:     '303548'
    playlist_hds_vodcrid: '303312'
    playlist_prodid:      '1/8694/6377#001'
    playlist_hds_prodid:  'Y/1774/0004/Z'
    hdsmanifest_prodid:   '1/700084/34b5ff8a05eb480a9d04d6bf032e46a'
    user_id:              '1237847'
rc3:
    mercury_url:          'http://mercury.rc3.itv.com'
    lithium_url:          'http://lithium.rc3.itv.com'
    bloom_status_url:     'http://bloomcms.rc3.itv.com/internal/status/api'
    ftp_host:             '89.151.100.137'
    ftp_login:            'itvbbrc3/mercuryftp'
    ftp_password:         'Password01'
    pay_metadata:         ''
    non_pay_metadata:     'http://89.151.100.137:8080/Metadata/CatchupAndArchive.meta'
    irdeto_pay_metadata:  ''
    temp_folder:          '/tmp/mdr'
    playlist_vodcrid:     '255854'
    playlist_hds_vodcrid: '303312'
    playlist_prodid:      '1/800735/2345#001'
    playlist_hds_prodid:  'Y/1774/0004/Z'
    user_id:              '1237847'
s01:
    mercury_url:          'http://s01-mercury.itv.com'
    lithium_url:          'http://s01-lithium-news.itv.com'
    bloom_status_url:     'http://s01-bloomcms.itv.com/internal/status/api'
    ftp_host:             's01-itvonlineftp.itv.com'
    ftp_login:            'mercuryftp'
    ftp_password:         '9d$]q1H&g+\>'
    pay_metadata:         'http://s01-onramp.itv.com/Metadata/CatchupAndArchiveNew.meta'
    non_pay_metadata:     'http://s01-onramp.itv.com/Metadata/CatchupAndArchive.meta'
    irdeto_pay_metadata:  'http://s01-onramp.itv.com/Metadata/CatchupAndArchivePay.meta'
    temp_folder:          '/tmp/mdr'
    playlist_vodcrid:     '303548'
    playlist_hds_vodcrid: '303312'
    playlist_prodid:      '1/7842/0277#001'
    playlist_hds_prodid:  '1/1918/0003/Z'
    hdsmanifest_prodid:   '1/700084/34b5ff8a05eb480a9d04d6bf032e46a'
    user_id:              '1237847'
i01:
    mercury_url:          'http://i01-mercury.itv.com'
    lithium_url:          'http://i01-lithium-news.itv.com'
    bloom_status_url:     'http://bloomcms.itvint01.ads/internal/status/internal/status/api'
    temp_folder:          '/tmp/mdr'
    playlist_vodcrid:     '323995'
    playlist_hds_vodcrid: '303312'
    playlist_prodid:      '1/800735/2345#001'
    playlist_hds_prodid:  'Y/1774/0004/Z'
    user_id:              '1237847'
live:
    mercury_url:          'http://mercury.itv.com'
    lithium_url:          'http://lithium-news.itv.com'
    bloom_status_url:     'http://bloomcms.itvonline.ads/internal/status/api'
    temp_folder:          '/tmp/mdr'
    playlist_vodcrid:     '255730'
    playlist_hds_vodcrid: '303312'
    playlist_prodid:      '1/8697/0022#001'
    playlist_hds_prodid:  '1/7941/0002#001'
    user_id:              '1200432'
