local:
    mercury_url:              'http://localhost:11323'
    lithium_url:              ''
    bloom_url:                'http://localhost:49940'
    bloom_status_url:         'http://localhost:49940/internal/status/api'
    publish_site:             'http://localhost:48940'
    origin:                   'http://localhost:31423'
    sherpa:                   'http://localhost:8096'
    alcatraz:                 'http://localhost:5681'
    playlist_vodcrid:         '301871'
    irdeto_catchup_rtmpe:     '1/800735/2345#001'
    irdeto_archive_f4m:       '1/700434/13666cdfecb940a786045a980b807d00#001'
    user_id:                  '1237847'
ft02:
    alcatraz_url:             'http://test-alcatraz.itv.com'
    mercury_url:              'http://test-mercury.itv.com'
    secure_mercury_url:       'http://test-secure.mercury.itv.com'
    lithium_url:              'http://test-lithium-news.itv.com'
    bloom_status_url:         'http://bloomcms.itvft02.ads/internal/status/api'
    ftp_host:                 's01-itvonlineftp.itv.com'
    ftp_login:                'mercuryftp'
    ftp_password:             '9d$]q1H&g+\>'
    pay_metadata:             'http://s01-onramp.itv.com/Metadata/CatchupAndArchiveNew.meta'
    non_pay_metadata:         'http://s01-onramp.itv.com/Metadata/CatchupAndArchive.meta'
    irdeto_pay_metadata:      'http://s01-onramp.itv.com/Metadata/CatchupAndArchivePay.meta'
    temp_folder:              '/tmp/mdr'
    generic_production:       '1/805537/320d95e6185e448abcf7e856efb6236e#001'
    youview_production:       '1/805537/320d95e6185e448abcf7e856efb6236e#001'
    dotcom_catchup_rtmpe:     '1/805537/320d95e6185e448abcf7e856efb6236e#001'
    dotcom_archive_rtmpe:     ''
    now_tv_hls_production:    '1/5163/1734#001'
    user_id:                  '1237847'
    itv1_vodcrid:             '328123'
    itv2_vodcrid:             '328126'
    itv3_vodcrid:             '328128'
    itv4_vodcrid:             '328132'
    citv_vodcrid:             '328135'
    itv1_production:          '1/368199/ebf7f12cf6204721b0a12eb0aec6dfe7#001'
    itv2_production:          '1/896647/b7ceeee5b60d47fabcfc70ec6c86df3e#001'
    itv3_production:          '1/730793/9ebfb13eea7043a5a1a158db0863473c#001'
    itv4_production:          '1/675188/29b2d2f1dc3e4dfaa9c05209c353bf65#001'
    citv_production:          '1/137741/c0960f4948924220a069d84b06029a5b#001'
    absolute_break_pattern:   '1/470886/fde4245558a3fb2c769989fbc#001'
    generic_break_pattern_1:  '1/615347/ba492459d9ca94c3b2fab9189#001'
    generic_break_pattern_2:  '1/200891/b00c64ca1aa7a1c69699fb00a#001'
    duration_break_pattern:   '1/587049/4be4742fd9f5454ddedd866ce#001'
    freesat_production:       '328120'
    error_log:                'http://test-mercury.itv.com/errorlog.aspx'
    splunk_host:              'https://ape.itvft02.ads:8089'
    playlist_service:         'https://test-origin-api.itv.com'
    playlist_production:      '1-5163-1734_001'
    smil_vodcrid:             '328968'
    no_renditions:            '1-3615-8762_001'
    no_assets_prodid:         '0-0000-0000_000'
i01:
    alcatraz_url:             'http://i01-alcatraz.itv.com'
    mercury_url:              'http://i01-mercury.itv.com'
    secure_mercury_url:       'http://i01-secure.mercury.itv.com'
    lithium_url:              'http://i01-lithium-news.itv.com'
    bloom_status_url:         'http://bloomcms.itvint01.ads/internal/status/api'
    temp_folder:              '/tmp/mdr'
    generic_production:       '1/840560/253114be3af4196c5926f634c#001'
    youview_production:       '2/268328/159c8#001'
    dotcom_catchup_rtmpe:     '1/419662/aac254712a8b8eb4934b22840#001'
    dotcom_archive_rtmpe:     '1/9310/0007#001'
    now_tv_hls_production:    '1/7842/0395#001'
    user_id:                  '62517' # kiran.hare@itv.com / password
    absolute_break_pattern:   '1/528854/443a345c1a845199fdcf93dc0#001'
    generic_break_pattern_1:  '1/209177/e711041f6bd71858ac49f4325#001'
    generic_break_pattern_2:  '1/716783/df8634f13a60c87653bf36b7a#001'
    duration_break_pattern:   '1/893311/7d7c540c7879576334257ef13#001'
    freesat_production:       '326543'
    error_log:                'http://i01-mercury.itv.com/errorlog.aspx'
    splunk_host:              'https://ape.itvint01.ads:8089'
    playlist_service:         'https://i01-origin-api.itv.com'
    playlist_production:      '1-7842-0395_001'
    smil_vodcrid:             '325808'
    no_renditions:            '1-0694-8337_001'
    no_assets_prodid:         '0-0000-0000_000'
live:
    alcatraz_url:             'http://alcatraz.itv.com'
    mercury_url:              'http://mercury.itv.com'
    secure_mercury_url:       'http://mercury.itv.com'
    lithium_url:              'http://lithium-news.itv.com'
    bloom_status_url:         'http://bloomcms.itvonline.ads/internal/status/api'
    temp_folder:              '/tmp/mdr'
    generic_production:       '2/1780/0001#001'
    youview_production:       '2/1780/0001#001'
    dotcom_catchup_rtmpe:     '2/1780/0001#001'
    dotcom_archive_rtmpe:     ''
    user_id:                  '1200432'
    error_log:                'http://mercury.itv.com/errorlog.aspx'
    splunk_host:              'https://ape.itvonline.ads:8089'
    playlist_production:      ''
