source 'http://rubygems.org'

gem 'savon', '<2.0'
gem 'cucumber'
gem 'rspec-expectations'
gem 'rake'
gem 'nokogiri'
gem 'simplecov'
gem 'json', '~> 1.7.7'
gem 'rest-client'
gem 'activesupport'
gem 'ingestrb', '>0.0.1', :git => 'git@github.com:ITV/ingestrb.git'
gem 'rspec'
