source 'https://rubygems.org'

gem 'savon', '<2.0'
gem 'cucumber'
gem 'rspec-expectations'
gem 'rake'
gem 'nokogiri', '<1.6.0'
gem 'simplecov'
gem 'json', '~> 1.7.7'
gem 'ingestrb', '>0.0.1', :git => 'git@github.com:ITV/ingestrb.git'
gem 'httparty'
gem 'rspec'
gem 'webmock'
